### ISSUE TITLE
Is this still working? 0.101.3

### ISSUE THREAD

**Issue by plainslice** [giu1io/sonos-player-modes-HASS#1]
Just found this and installed it manually. Service shows up but when I try to activate it its not working :/ 

Either nothing happens on the front end, and I see no response in sonos, or Ill get the following error on the front end: 

Failed to call service sonos_player_modes/set_mode. UPnP Error 712 received: Play mode not supported from xxx.xxx.x.xx

**Comment by giu1io** [comment]
Hi @pizzapants,
It's working for me in 0.101.3! My Sonos is on the latest version too.

[![Demo Sonos Player Set Mode Repeat](https://media.giphy.com/media/YkJg8YpwsJ30Uthe8R/giphy.gif)](https://media.giphy.com/media/YkJg8YpwsJ30Uthe8R/source.mp4)

What data are you sending to the service?

**Comment by plainslice** [comment]
Weird! It looks like its working fine now. And it looks like the error I was getting was calling a room when it was part of a group (and not the master speaker). 

Thanks for the reply! Do you still have this in HACS? I couldnt find it and would love to be able to install it that way

**Comment by giu1io** [comment]
Oh that makes sense. I think you need to always call the master speaker. 

To install it with HACS just go to Settings -> Add Custom Repository and paste the link to the repo in there. I installed it that way and it works great.
I didn't ask to have it added to the HACS Store yet, that's why you can't find it there.

**Comment by plainslice** [comment]
Awesome, thanks. If I can bug you with one other question, do you use node red? For some reason, I cant get it to trigger and Im wondering if Im formatting something wrong here. 


![Annotation 2019-11-09 100414](https://user-images.githubusercontent.com/25411305/68532258-5f1aba00-02d8-11ea-8575-66d8c282c664.png)

**Comment by giu1io** [comment]
No I don't use it. Can you try to move the entity_id into the data json? Probably it won't make any difference but that's that seems out-of-place to me.
