### ISSUE TITLE
Failed to call service sonos_player_modes/set_mode. Service not found.

### ISSUE THREAD

**Issue by timdonovanuk** [giu1io/sonos-player-modes-HASS#3]
I've installed via HACS. I also put `sonos_player_modes:` in my configuration.yaml for good measure. But the service is not available.  Nothing in the logs either :(

**Comment by giu1io** [comment]
Hi @timdonovanuk,
Did you restart home assistant after adding `sonos_player_modes:` to your `configuration.yaml`? It should show up under services like this:
![image](https://user-images.githubusercontent.com/6680957/93871974-c6aedd80-fccf-11ea-9a65-1cbcfa89ee56.png)

**Comment by timdonovanuk** [comment]
Weird, I had restarted a few times! I tried uninstalling and reinstalling it, and it looks like the service is there now. Thanks anyway! :) And thanks for the service!!
