### ISSUE TITLE
Broken in HA 2021.7+

### ISSUE THREAD

**Issue by jeremywillans** [giu1io/sonos-player-modes-HASS#5]
This feature no longer works - @giu1io I would recommend archiving this project.

media_player_entities has been removed in [Core PR#50277](https://github.com/home-assistant/core/pull/50277)

However - as these already exist in Core HA, just separately, if you use this custom component, simply re-write your code to perform these actions individually, however specify a delay of 1 sec between actions to ensure they are processed by the speaker.
- [repeat](https://www.home-assistant.io/integrations/media_player/#service-media_playerrepeat_set) 
- [shuffle](https://www.home-assistant.io/integrations/media_player/#service-media_playershuffle_set)

**Comment by giu1io** [comment]
Thank's for the heads up. I have updated the README and archived the repository!
